# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
# Stage 1: Build the application
FROM node:18-alpine AS builder

# Set working directory
WORKDIR /app

# Copy package files and install dependencies
COPY package.json package-lock.json ./
RUN npm install

# Copy the application source code
COPY tsconfig.json ./
COPY src ./src

# Build the application
RUN npm run build

# Stage 2: Run the application
FROM node:18-alpine

# Set working directory
WORKDIR /app

# Copy built files from the builder stage
COPY --from=builder /app/build ./build
COPY package.json ./

# Install only production dependencies
RUN npm install --omit=dev

# Set environment variable for the API key
ENV API_KEY=your_nps_api_key_here

# Start the application
ENTRYPOINT ["node", "./build/index.js"]
